version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Skipping tests; no jest configured"
      - echo "Bunccddild phmdsasehas  completed"

artifacts:
  files:
    - '**/*'
 

