version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm test
      - zip -r app.zip .  # zip files for Elastic Beanstalk deployment

artifacts:
  files:
    - app.zip

